sudo: required
language: node_js
dist: trusty
node_js:
- '12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  code_climate:
    repo_token: 2fb826206cbbdeefc0bedc2e7935f1fd5e9fdca31b9290614b3d22ac469583e8
  chrome: stable
env:
  global:
  - TRAVIS=true
